version: '3.9'

services:

  db:
    image: mysql:8.0
    container_name: mysql_db_2
    restart: always
    environment:
      MYSQL_DATABASE: usecase_doctor
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  backend:
    build: ./sop_django
    container_name: django_backend_2
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: usecase_doctor
      DB_USER: root
      DB_PASSWORD: root
      DB_PORT: 3306
    ports:
      - "8000:8000"

  frontend:
    build: ./sop-django-ui
    container_name: angular_frontend_2
    restart: always
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  mysql_data:
